name: Update all index.md files

on:
  push:
    paths:
      - 'Scripts/**'
      - 'Scripts/Scripts-for-linux-and-macos/**'
      - 'codeeditors/**'
      - 'tools/**'
      - 'games/**'

jobs:
  update-indexes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate index.md for each folder
        run: |
          generate_index() {
            folder="$1"
            echo "# 📜 ${folder##*/} Directory" > "$folder/index.md"
            echo "" >> "$folder/index.md"

            find "$folder" -maxdepth 1 -type f \
              ! -name "index.md" \
              ! -name "scripts.css" \
              -exec basename {} \; | sort | while read fname; do
                echo "- [$fname]($fname)" >> "$folder/index.md"
            done
          }

          generate_index Scripts
          generate_index Scripts/Scripts-for-linux-and-macos
          generate_index codeeditors
          generate_index tools
          generate_index games

      - name: Commit changes
        run: |
          git config user.name "Auto Index Bot"
          git config user.email "bot@example.com"
          git add Scripts/index.md Scripts/Scripts-for-linux-and-macos/index.md codeeditors/index.md tools/index.md games/index.md
          git commit -m "Auto-update sorted index.md files"
          git push
